### ISSUE TITLE
Periodic table source

### ISSUE THREAD

**Issue by ghost** [Maxzilla60/Spelling-with-Elements#6]
Hi! First of all, I really like the project you're working on.

But that's not really what my question is about. I'd like to know how you got all that Periodic Table data and if I'm allowed to use it.

**Comment by ghost** [comment]
I was talking about https://github.com/Maxzilla60/Spelling-with-Elements/blob/master/PeriodicTableJSON.js

**Comment by Zayceur** [comment]
If you read this commit (https://github.com/Maxzilla60/Spelling-with-Elements/commit/86a4b3850bb9d42a8df219f6490b97001187f98a) you will see where I found it.

**Comment by ghost** [comment]
@Zayceur Thanks! I'll definitely be able to use this for some fun projects!
